### ISSUE TITLE
EF6 support

### ISSUE THREAD

**Issue by bnuzhouwei** [dmdbms/Microsoft.EntityFrameworkCore.Dm#2]

**Comment by aaasoft** [comment]
Hi,I'm not the employee of the DaMeng corp,I just decompile the dll from DaMeng and publish nupkg file to nuget.org.So I have no plan to support EF6 in this repo now.If you make a pull request to support EF6,it's welcome.

**Comment by aaasoft** [comment]
Hi,now DaMeng corp support EntityFrameworkCore 6.0 now.I publish new package to nuget.org.you can try it.
https://www.nuget.org/packages/dmdbms.Microsoft.EntityFrameworkCore.Dm/6.0.16.16649
