### ISSUE TITLE
程序在执行时发生错误。

### ISSUE THREAD

**Issue by emmmmm566** [dmdbms/Microsoft.EntityFrameworkCore.Dm#4]
亲。我使用该方法库生成了相关的实体类型。但在执行过程中无法运行。
程序定位在此处被停止
![image](https://user-images.githubusercontent.com/41360364/207769936-43314ee0-c721-4a2b-902e-09141c056754.png)

**Comment by yangzhongke** [comment]
达梦官方的efcore6的库有bug，导致这个库也有bug，所以这个版本不要用。等官方修复了bug再说吧。
你可以先用5.0版本的。

**Comment by emmmmm566** [comment]
亲。我搞了一下午。终于找到问题了。
![image](https://user-images.githubusercontent.com/41360364/207807941-07e1e66b-b762-4d59-bf75-c8a319551673.png)
这样的配置项是正确的。
![image](https://user-images.githubusercontent.com/41360364/207808257-fc8407ee-6a5b-414d-8b54-3ab005d85748.png)
![image](https://user-images.githubusercontent.com/41360364/207808356-86a3a363-2821-4620-af47-79c25307a740.png)
我通过手动更改dll,和添加微软的EF程序包。
在.NET Core 6达到了如下的效果
![image](https://user-images.githubusercontent.com/41360364/207808733-5bb59d2e-b91c-428d-ac02-8b52fb260dfe.png)
而dll包不存在执行上的问题。

具体的问题应该产生在 nuget包中的依赖不完全,或者支持的.net版本太低而导致执行产生异常。
![image](https://user-images.githubusercontent.com/41360364/207809432-72a4a982-df15-4a33-9af1-df3dee74b83b.png)
![image](https://user-images.githubusercontent.com/41360364/207809664-805fcbbc-f18e-4728-a7f1-734c38ef9d71.png)

**Comment by aaasoft** [comment]
你好，现在达梦官方已经支持EntityFrameworkCore 6.0了.我已经把新的包发布到nuget上了，你可以试试。
https://www.nuget.org/packages/dmdbms.Microsoft.EntityFrameworkCore.Dm/6.0.16.16649
