### ISSUE TITLE
不能查询，一查询就报错

### ISSUE THREAD

**Issue by itchangc** [dmdbms/Microsoft.EntityFrameworkCore.Dm#5]
![image](https://user-images.githubusercontent.com/40175292/208371352-a6ecd61c-7fda-468b-aa01-4ba4e48fe721.png)

**Comment by itchangc** [comment]
System.InvalidCastException:“Unable to cast object of type 'ConcreteColumnExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.CaseExpression'.”

**Comment by itchangc** [comment]
![image](https://user-images.githubusercontent.com/40175292/208371480-3e02489b-48d1-4dbf-a7f1-a26fe5f63f3d.png)

**Comment by itchangc** [comment]
![image](https://user-images.githubusercontent.com/40175292/208371556-bbec79ff-b111-4693-985e-7c372c587dba.png)

这个源码里面的Tests.NET6  的demo 也不能做查询

**Comment by yangzhongke** [comment]
当前.NET6的代码有问题，不要用。

**Comment by yangzhongke** [comment]
https://github.com/dmdbms/Microsoft.EntityFrameworkCore.Dm/issues/4

**Comment by aaasoft** [comment]
6.0分支的README.md文件中我添加了警告，现在不要使用6.0版本。

**Comment by itchangc** [comment]
> 6.0分支的README.md文件中我添加了警告，现在不要使用6.0版本。

我公司项目中用的6.0的EF CORE 现在客户要支持达梦，你们达梦ef core 6.0 有bug，现在该怎么办呢

**Comment by aaasoft** [comment]
> > 6.0分支的README.md文件中我添加了警告，现在不要使用6.0版本。
> 
> 我公司项目中用的6.0的EF CORE 现在客户要支持达梦，你们达梦ef core 6.0 有bug，现在该怎么办呢

我们不是达梦公司官方哈，只是反编译了达梦的dll，上传到NuGet上方便大家使用。建议你联系达梦公司提供技术支持。如果你也能参与到这个代码库就更好了。

**Comment by itchangc** [comment]
刚刚我下载了最新的达梦windows安装包，里面的离线驱动EFCore.Dm6.0 除了不能生成迁移文件。其它的功能都可以用。
add-migration  文件名  这个功能不能用，我刚刚给达梦公司发了邮件。

但是我用你们提供的包生成的迁移文件。
此时用官方的包 update-database 是没问题的。
我生成数据库后，用官方离线包，做了增加、查询 是没有问题的。

**Comment by emmmmm566** [comment]
对，用Dm8的最新的core6包的dll。
由于我只是需要生成Context文件,和进行简单的CRUD,并没有使用到当前的开发库。
用Dm官方的dll能够完成这些基本操作。

**Comment by aaasoft** [comment]
你好，现在达梦官方已经支持EntityFrameworkCore 6.0了.我已经把新的包发布到nuget上了，你可以试试。
https://www.nuget.org/packages/dmdbms.Microsoft.EntityFrameworkCore.Dm/6.0.16.16649
