### ISSUE TITLE
生成实体类报错:Unable to resolve service for type 

### ISSUE THREAD

**Issue by njroyin** [dmdbms/Microsoft.EntityFrameworkCore.Dm#6]
生成实体类报错
执行 dotnet ef dbcontext scaffold "server=xxxx;Schema=xxxx;port=5236;user=SYSDBA;password=xxxx" Microsoft.EntityFrameworkCore.Dm --context MyDbContext --context-dir Context --output-dir Entities --no-onconfiguring --no-pluralize -f

Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1[Microsoft.EntityFrameworkCore.DbLoggerCategory+Scaffolding]' while attempting to activate 'Microsoft.EntityFrameworkCore.Dm.Scaffolding.Internal.DmDatabaseModelFactory'.

net 6.0
dmdbms.Microsoft.EntityFrameworkCore.Dm 5.0.3
dmdbms.DmProvider 1.1.3

**Comment by yangzhongke** [comment]
这里不是达梦官网库。现在不支持.NET 6。请联系达梦官方。

**Comment by aaasoft** [comment]
你好，现在达梦官方已经支持EntityFrameworkCore 6.0了.我已经把新的包发布到nuget上了，你可以试试。
https://www.nuget.org/packages/dmdbms.Microsoft.EntityFrameworkCore.Dm/6.0.16.16649
