### ISSUE TITLE
不支持ABP（aspnetboilerplate）的工作单元（事务）

### ISSUE THREAD

**Issue by dacaba** [dmdbms/Microsoft.EntityFrameworkCore.Dm#8]
在.net6的ABP（aspnetboilerplate）中使用达梦数据库的时候，不支持工作单元（事务），集成后运行报错。帮忙处理一下这个问题。

**Comment by aaasoft** [comment]
> 在.net6的ABP（aspnetboilerplate）中使用达梦数据库的时候，不支持工作单元（事务），集成后运行报错。帮忙处理一下这个问题。

此代码仓库不是由达梦公司维护，如果有Pull request，欢迎提交。如果需要技术支持，请联系达梦公司。
